# Generated by Django 4.1.7 on 2023-03-05 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_rename_enrollement_id_submission_enrollment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='choice_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.choice'),
        ),
    ]
