# Generated by Django 4.1.7 on 2023-03-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0004_alter_submission_choice_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='choice_id',
        ),
        migrations.AddField(
            model_name='submission',
            name='choice_id',
            field=models.ManyToManyField(to='onlinecourse.choice'),
        ),
    ]
