# Generated by Django 4.1.7 on 2023-03-05 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0005_remove_submission_choice_id_submission_choice_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='choice_id',
            new_name='choices',
        ),
    ]
